language: node_js
node_js: 10.13.0
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf public
    - npm install
    
script:
    - hugo
    - gulp
    - echo 'Build done!'
after_success:
    - git config --global user.email "incomparable9527@foxmail.com"
    - git config --global user.name "Fan"
    - git clone https://${ACCESS_TOKEN}@github.com/Fantasy9527/alili.tech.git container
    - rm -rf container/*
    - cp -r public/* container 
    - cd container
    - git add .
    - git commit -m 'Travis upate blog'
    - git push -u origin gh-pages -f
    - curl -d "" ${DEPLOY_API}
